#!/bin/bash
echo "## System"
echo "Name | Version"
echo "---- | -------"

# OS
echo "OS |" $(lsb_release -ds)
# GPU
echo "GPU |" $(nvidia-smi --query-gpu=gpu_name --format=csv,noheader)
# Python Version
echo "Python |" $(python -V 2>&1)

# Python Packages
PKGS=(Keras TensorFlow NumPy)
for PKG in ${PKGS[*]}; do
	# Convert to lowercase
	pkg=$(echo "$PKG" | tr '[:upper:]' '[:lower:]')
	
	echo  $PKG "|" $(python -W ignore -c "import ${pkg}; print(${pkg}.__version__)" 2> /dev/null)
done

echo ""
echo "_System specs autogenerated by \
      [GetSpecs](https://github.com/OisinMoran/GetSpecs \
      'GetSpecs GitHub Repository')_"
